"""
Language configuration and translations for the xG prediction application.
"""

# Language configurations
LANGUAGES = {
    "🇮🇩 Bahasa Indonesia": "id",
    "🇺🇸 English": "en"
}

# Complete translations dictionary
TRANSLATIONS = {
    "id": {
        # App Title and Navigation
        "app_title": "⚽ Antarmuka Prediksi Expected Goals (xG)",
        "navigation": "Navigasi",
        "predict_from_dataset": "Prediksi xG dari Dataset",
        "simulate_custom_shot": "Simulasi Tembakan Custom",
        
        # Dataset Prediction Page
        "predict_batch_header": "📈 Prediksi xG untuk Kumpulan Tembakan",
        "predict_batch_desc": "Upload file CSV berisi data tembakan untuk mendapatkan prediksi xG untuk setiap event.",
        "required_columns": "📋 Kolom yang Wajib Ada di File CSV Anda",
        "time_context": "🕐 Waktu & Konteks:",
        "player_position": "👤 Pemain & Posisi:",
        "shot_technique": "🎯 Teknik Tembakan:",
        "shot_location": "📍 Lokasi Tembakan:",
        "shot_context": "⚽ Konteks Tembakan:",
        "optional_analysis": "📊 Opsional (untuk analisis):",
        "tip_message": "💡 **Tips:** Semua field ID harus menggunakan format StatsBomb. Field boolean harus berupa 0 atau 1.",
        "detailed_descriptions": "🔍 Lihat Deskripsi Kolom Lengkap",
        "choose_csv": "Pilih file CSV",
        "upload_preview": "Preview Data yang Diupload",
        "missing_columns": "File yang diupload tidak memiliki kolom yang diperlukan berikut:",
        "calculating_xg": "Menghitung xG...",
        "clear_data": "Hapus Data",
        "results_predictions": "Hasil dengan Prediksi xG",
        "summary_stats": "📊 Statistik Ringkasan",
        "total_shots": "Total Tembakan",
        "average_xg": "Rata-rata xG",
        "total_xg": "Total xG",
        "goals_scored": "Gol Tercetak",
        "shot_map": "Peta Tembakan",
        "half_pitch_map": "Peta Setengah Lapangan",
        "visualization_type": "Jenis Visualisasi",
        "shot_map_option": "Shot Map",
        "heat_map_option": "Heat Map",
        "download_section": "📥 Unduh Hasil",
        "download_csv": "Unduh Data CSV",
        "download_full_pitch": "Unduh Peta Lapangan Penuh",
        "download_half_pitch": "Unduh Peta Setengah Lapangan",
        "download_csv_desc": "Download hasil prediksi xG dalam format CSV",
        "download_viz_desc": "Download visualisasi shot map sebagai gambar PNG",
        "summary_stats_error": "Tidak dapat menampilkan statistik ringkasan:",
        "predictions_accurate": "Ini tidak mempengaruhi prediksi utama - prediksi tetap akurat.",
        "column_reorder_error": "Tidak dapat mengurutkan ulang kolom:",
        "prediction_error": "Terjadi kesalahan saat prediksi:",
        "data_mismatch": "Ini mungkin karena ketidakcocokan antara data di file Anda dengan data yang digunakan untuk melatih dummy model. Dummy model sangat sederhana dan mengharapkan rentang nilai tertentu.",
        
        # Custom Shot Page
        "simulate_header": "🛠️ Simulasi Skenario Tembakan Custom",
        "simulate_desc": "Gunakan kontrol di bawah ini untuk mendefinisikan tembakan tunggal dan menghitung xG-nya.",
        "shot_characteristics": "Karakteristik Tembakan",
        "play_pattern": "Pola Permainan",
        "player_position_select": "Posisi Pemain",
        "shot_technique_select": "Teknik Tembakan",
        "body_part": "Bagian Tubuh",
        "shot_type": "Jenis Tembakan",
        "event_before": "Event Sebelum Tembakan",
        "shot_context_section": "Konteks Tembakan",
        "open_goal": "Gawang Kosong",
        "one_on_one": "Satu Lawan Satu",
        "aerial_won": "Duel Udara Dimenangkan",
        "under_pressure": "Di Bawah Tekanan",
        "time_of_shot": "Waktu Tembakan",
        "minute": "Menit",
        "second": "Detik",
        "additional_features": "Fitur Tambahan",
        "period": "Babak",
        "first_half": "Babak Pertama",
        "second_half": "Babak Kedua",
        "shot_first_time": "Tembakan Langsung (First Time)",
        "shot_key_pass": "Hasil dari Key Pass",
        "additional_features": "Fitur Tambahan",
        "period": "Babak",
        "first_half": "Babak Pertama",
        "second_half": "Babak Kedua",
        "shot_first_time": "Tembakan Tanpa Kontrol",
        "shot_key_pass": "Tembakan dari Key Pass",
        "shot_location_xy": "Lokasi Tembakan (x, y)",
        "start_x": "Koordinat X Awal",
        "start_y": "Koordinat Y Awal",
        "shot_location_preview": "Preview Lokasi Tembakan",
        "interactive_pitch_title": "Klik pada lapangan untuk memilih lokasi tembakan",
        "click_instruction": "💡 Gunakan slider atau tombol area di bawah untuk mengatur koordinat tembakan:",
        "current_coordinates": "Koordinat saat ini:",
        "quick_zone_selection": "Pilih zona cepat:",
        "calculate_xg": "Hitung xG",
        "predicted_xg": "xG Prediksi",
        "simulated_shot_xg": "xG Tembakan Simulasi",
        "prediction_error_custom": "Terjadi kesalahan saat prediksi:",
        
        # Custom shots management
        "custom_shots_manager": "Manajemen Tembakan Kustom",
        "shot_name": "Nama Tembakan",
        "add_to_collection": "Tambah ke Koleksi",
        "shot_added_success": "Tembakan berhasil ditambahkan ke koleksi!",
        "model_performance": "Performa Model",
        "prediction_time": "Waktu Prediksi",
        "custom_shots_collection": "Koleksi Tembakan Kustom",
        "shots_count": "Jumlah Tembakan",
        "average_xg": "Rata-rata xG",
        "total_expected_goals": "Total Expected Goals",
        "download_custom_shots": "Unduh Data Tembakan Kustom",
        "clear_all_shots": "Hapus Semua Tembakan",
        "remove_shot": "Hapus",
        "custom_shots_visualization": "Visualisasi Tembakan Kustom",
        "no_custom_shots": "Belum ada tembakan kustom yang disimpan",
        "enter_shot_name": "Masukkan nama tembakan",
        "shot_name_exists": "Nama tembakan sudah ada, gunakan nama lain",
        
        # Column descriptions
        "minute_desc": "Menit pertandingan (0-120)",
        "second_desc": "Detik dalam menit (0-59)",
        "play_pattern_desc": "ID pola permainan",
        "type_before_desc": "ID event sebelum tembakan",
        "position_desc": "ID posisi pemain",
        "under_pressure_desc": "Di bawah tekanan (0/1)",
        "shot_technique_desc": "ID teknik tembakan",
        "shot_body_part_desc": "ID bagian tubuh yang digunakan",
        "shot_type_desc": "ID jenis tembakan",
        "start_x_desc": "Koordinat X (0-120)",
        "start_y_desc": "Koordinat Y (0-80)",
        "shot_open_goal_desc": "Gawang kosong (0/1)",
        "shot_one_on_one_desc": "Satu lawan satu (0/1)",
        "shot_aerial_won_desc": "Duel udara dimenangkan (0/1)",
        "shot_outcome_desc": "Hasil aktual (1=Gol, 0=Bukan Gol)",
        "period_desc": "ID babak pertandingan (1=Babak Pertama, 2=Babak Kedua)",
        "shot_first_time_desc": "Tembakan tanpa kontrol/first time (0/1)",
        "shot_key_pass_desc": "Tembakan berasal dari key pass (0/1)",
        "team_name": "Nama Tim",
        "team_name_desc": "Nama tim (opsional)",
        "player_name": "Nama Pemain",
        "player_name_desc": "Nama pemain (opsional)",
        
        # ID Mappings
        "play_pattern_ids": "**ID Pola Permainan:**",
        "play_pattern_values": "1=Permainan Biasa, 2=Dari Tendangan Sudut, 3=Dari Tendangan Bebas, 4=Dari Lemparan Ke Dalam, 6=Dari Serangan Balik, 7=Dari Tendangan Gawang, 9=Dari Kick Off",
        "position_ids": "**ID Posisi:**",
        "position_values": "23=Striker, 25=Striker Kedua, 19=Gelandang Serang Tengah, 17=Sayap Kanan, 21=Sayap Kiri, 12=Gelandang Kanan, 16=Gelandang Kiri",
        "shot_technique_ids": "**ID Teknik Tembakan:**",
        "shot_technique_values": "93=Normal, 95=Voli, 91=Setengah Voli, 90=Sundulan Menyambar, 92=Lob, 94=Tendangan Gunting, 89=Tumit",
        "body_part_ids": "**ID Bagian Tubuh:**",
        "body_part_values": "40=Kaki Kanan, 38=Kaki Kiri, 37=Kepala, -1=Lainnya",
        "shot_type_ids": "**ID Jenis Tembakan:**",
        "shot_type_values": "87=Permainan Terbuka, 62=Tendangan Bebas, 88=Penalti, 61=Dari Tendangan Sudut, -1=Lainnya",
        "event_before_ids": "**ID Event Sebelum Tembakan:**",
        "event_before_values": "30=Operan, 43=Menggiring, 14=Dribel, 2=Rebut Bola, 10=Intersepsi, 38=Kesalahan Kontrol",
        
        # Mappings for UI options
        "regular_play": "Permainan Biasa",
        "from_corner": "Dari Tendangan Sudut",
        "from_free_kick": "Dari Tendangan Bebas",
        "from_throw_in": "Dari Lemparan Ke Dalam",
        "from_counter": "Dari Serangan Balik",
        "from_goal_kick": "Dari Tendangan Gawang",
        "from_kick_off": "Dari Kick Off",
        
        "striker": "Striker",
        "secondary_striker": "Striker Kedua",
        "center_attacking_midfield": "Gelandang Serang Tengah",
        "right_wing": "Sayap Kanan",
        "left_wing": "Sayap Kiri",
        "right_midfield": "Gelandang Kanan",
        "left_midfield": "Gelandang Kiri",
        
        "normal": "Normal",
        "volley": "Voli",
        "half_volley": "Setengah Voli",
        "diving_header": "Sundulan Menyambar",
        "lob": "Lob",
        "overhead_kick": "Tendangan Gunting",
        "backheel": "Tumit",
        
        "right_foot": "Kaki Kanan",
        "left_foot": "Kaki Kiri",
        "head": "Kepala",
        "other": "Lainnya",
        
        "open_play": "Permainan Terbuka",
        "free_kick": "Tendangan Bebas",
        "penalty": "Penalti",
        "from_corner_shot": "Dari Tendangan Sudut",
        "other_shot": "Lainnya",
        
        "pass": "Operan",
        "carry": "Menggiring",
        "dribble": "Dribel",
        "ball_recovery": "Rebut Bola",
        "interception": "Intersepsi",
        "miscontrol": "Kesalahan Kontrol",
        
        # Error messages
        "model_load_error": "Gagal memuat model. Silakan periksa file model.",
        "model_required": "Model diperlukan untuk mengakses fitur prediksi.",
        "model_file_requirements": "Persyaratan File Model",
        "model_file_name": "Nama file: Harus tepat xg_model.joblib",
        "model_file_format": "Format: Joblib-serialized scikit-learn pipeline",
        "model_file_size": "Ukuran: Biasanya 1-50 MB tergantung kompleksitas model",
        "model_features_title": "Fitur Input Model:",
        "model_features_desc": "Model harus mendukung 19 fitur input berikut:",
        "troubleshooting": "Pemecahan Masalah",
        "no_model_file": "Jika Anda tidak memiliki file model:",
        "train_model": "Latih model menggunakan data Anda",
        "save_model": "Simpan sebagai: joblib.dump(model, 'xg_model.joblib')",
        "place_model": "Tempatkan di:",
        "file_not_loading": "Jika file ada tapi tidak dapat dimuat:",
        "check_permissions": "Periksa izin akses file",
        "valid_joblib": "Pastikan file joblib valid",
        "verify_compatibility": "Verifikasi kompatibilitas model",
        "quick_help": "Bantuan Cepat",
        "steps_to_fix": "Langkah-langkah Perbaikan:",
        "locate_model": "Temukan file model Anda",
        "copy_to_root": "Salin ke direktori root",
        "restart_app": "Restart aplikasi",
        "available_features": "Fitur yang Tersedia",
        "after_model_setup": "Setelah setup model:",
        "advanced_visualizations": "Visualisasi lanjutan",
        "check_model_again": "🔄 Periksa Model Lagi",
        "click_refresh": "Klik tombol refresh di bawah untuk memeriksa lagi",
        "model_not_found_title": "Model File Tidak Ditemukan",
        "required_action": "Tindakan yang Diperlukan",
        "copy_model_instruction": "Silakan salin file model yang sudah dilatih",
        "to_path": "ke",
        "model_missing_during_work": "Model Hilang Saat Bekerja",
        "work_preserved": "Pekerjaan Anda Telah Disimpan",
        "dont_worry": "Jangan khawatir, data Anda aman",
        "simulation_state_saved": "Status simulasi tersimpan",
        "settings_preserved": "Pengaturan tetap ada",
        "quick_fix": "Perbaikan Cepat",
        "restore_model": "Kembalikan file model",
        "click_continue": "Klik tombol lanjutkan di bawah",
        "continue_work": "🔄 Lanjutkan Pekerjaan",
        "model_still_missing": "Model masih belum ditemukan. Pastikan file sudah ditempatkan dengan benar.",
        "no_shot_outcome": "N/A (tidak ada kolom shot_outcome)",
        "error_prefix": "Error:",
        
        # Language switcher
        "language": "Bahasa",
        "switch_language": "Ganti Bahasa"
    },
    
    "en": {
        # App Title and Navigation
        "app_title": "⚽ Expected Goals (xG) Prediction Interface",
        "navigation": "Navigation",
        "predict_from_dataset": "Predict xG from Dataset",
        "simulate_custom_shot": "Simulate Custom Shot",
        
        # Dataset Prediction Page
        "predict_batch_header": "📈 Predict xG for a Batch of Shots",
        "predict_batch_desc": "Upload a CSV file with shot data to get xG predictions for each event.",
        "required_columns": "📋 Required Columns in Your CSV File",
        "time_context": "🕐 Time & Context:",
        "player_position": "👤 Player & Position:",
        "shot_technique": "🎯 Shot Technique:",
        "shot_location": "📍 Shot Location:",
        "shot_context": "⚽ Shot Context:",
        "optional_analysis": "📊 Optional (for analysis):",
        "tip_message": "💡 **Tip:** All ID fields should use StatsBomb format. Boolean fields should be 0 or 1.",
        "detailed_descriptions": "🔍 See Detailed Column Descriptions",
        "choose_csv": "Choose a CSV file",
        "upload_preview": "Uploaded Data Preview",
        "missing_columns": "The uploaded file is missing the following required columns:",
        "calculating_xg": "Calculating xG...",
        "clear_data": "Clear Data",
        "results_predictions": "Results with xG Predictions",
        "summary_stats": "📊 Summary Statistics",
        "total_shots": "Total Shots",
        "average_xg": "Average xG",
        "total_xg": "Total xG",
        "goals_scored": "Goals Scored",
        "shot_map": "Shot Map",
        "half_pitch_map": "Half Pitch Map",
        "visualization_type": "Visualization Type",
        "shot_map_option": "Shot Map",
        "heat_map_option": "Heat Map",
        "download_section": "📥 Download Results",
        "download_csv": "Download CSV Data",
        "download_full_pitch": "Download Full Pitch Map",
        "download_half_pitch": "Download Half Pitch Map",
        "download_csv_desc": "Download xG prediction results as CSV file",
        "download_viz_desc": "Download shot map visualization as PNG image",
        "summary_stats_error": "Could not display summary statistics:",
        "predictions_accurate": "This doesn't affect the main predictions - they are still accurate.",
        "column_reorder_error": "Could not reorder columns:",
        "prediction_error": "An error occurred during prediction:",
        "data_mismatch": "This might be due to a mismatch between the data in your file and the data the dummy model was trained on. The dummy model is very simple and expects specific value ranges.",
        
        # Custom Shot Page
        "simulate_header": "🛠️ Simulate a Custom Shot Scenario",
        "simulate_desc": "Use the controls below to define a single shot and calculate its xG.",
        "shot_characteristics": "Shot Characteristics",
        "play_pattern": "Play Pattern",
        "player_position_select": "Player Position",
        "shot_technique_select": "Shot Technique",
        "body_part": "Body Part",
        "shot_type": "Shot Type",
        "event_before": "Event Before Shot",
        "shot_context_section": "Shot Context",
        "open_goal": "Open Goal",
        "one_on_one": "One on One",
        "aerial_won": "Aerial Won",
        "under_pressure": "Under Pressure",
        "time_of_shot": "Time of Shot",
        "minute": "Minute",
        "second": "Second",
        "additional_features": "Additional Features",
        "period": "Period",
        "first_half": "First Half",
        "second_half": "Second Half",
        "shot_first_time": "First Time Shot",
        "shot_key_pass": "From Key Pass",
        "additional_features": "Additional Features",
        "period": "Period",
        "first_half": "First Half",
        "second_half": "Second Half",
        "shot_first_time": "First Time Shot",
        "shot_key_pass": "Shot from Key Pass",
        "shot_location_xy": "Shot Location (x, y)",
        "start_x": "Start X Coordinate",
        "start_y": "Start Y Coordinate",
        "shot_location_preview": "Shot Location Preview",
        "interactive_pitch_title": "Click on the pitch to select shot location",
        "click_instruction": "💡 Use sliders or area buttons below to set shot coordinates:",
        "current_coordinates": "Current coordinates:",
        "quick_zone_selection": "Quick zone selection:",
        "calculate_xg": "Calculate xG",
        "predicted_xg": "Predicted xG",
        "simulated_shot_xg": "Simulated Shot xG",
        "prediction_error_custom": "An error occurred during prediction:",
        
        # Custom shots management
        "custom_shots_manager": "Custom Shots Manager",
        "shot_name": "Shot Name",
        "add_to_collection": "Add to Collection",
        "shot_added_success": "Shot successfully added to collection!",
        "model_performance": "Model Performance",
        "prediction_time": "Prediction Time",
        "custom_shots_collection": "Custom Shots Collection",
        "shots_count": "Number of Shots",
        "average_xg": "Average xG",
        "total_expected_goals": "Total Expected Goals",
        "download_custom_shots": "Download Custom Shots Data",
        "clear_all_shots": "Clear All Shots",
        "remove_shot": "Remove",
        "custom_shots_visualization": "Custom Shots Visualization",
        "no_custom_shots": "No custom shots saved yet",
        "enter_shot_name": "Enter shot name",
        "shot_name_exists": "Shot name already exists, use a different name",
        
        # Column descriptions
        "minute_desc": "Match minute (0-120)",
        "second_desc": "Second in minute (0-59)",
        "play_pattern_desc": "Play pattern ID",
        "type_before_desc": "Event before shot ID",
        "position_desc": "Player position ID",
        "under_pressure_desc": "Under pressure (0/1)",
        "shot_technique_desc": "Shot technique ID",
        "shot_body_part_desc": "Body part used ID",
        "shot_type_desc": "Shot type ID",
        "start_x_desc": "X coordinate (0-120)",
        "start_y_desc": "Y coordinate (0-80)",
        "shot_open_goal_desc": "Open goal (0/1)",
        "shot_one_on_one_desc": "One on one (0/1)",
        "shot_aerial_won_desc": "Aerial won (0/1)",
        "shot_outcome_desc": "Actual result (1=Goal, 0=No Goal)",
        "period_desc": "Match period ID (1=First Half, 2=Second Half)",
        "shot_first_time_desc": "First-time shot (0/1)",
        "shot_key_pass_desc": "Shot resulting from key pass (0/1)",
        "team_name": "Team Name",
        "team_name_desc": "Team name (optional)",
        "player_name": "Player Name",
        "player_name_desc": "Player name (optional)",
        
        # ID Mappings
        "play_pattern_ids": "**Play Pattern IDs:**",
        "play_pattern_values": "1=Regular Play, 2=From Corner, 3=From Free Kick, 4=From Throw-in, 6=From Counter, 7=From Goal Kick, 9=From Kick Off",
        "position_ids": "**Position IDs:**",
        "position_values": "23=Striker, 25=Secondary Striker, 19=Center Attacking Midfield, 17=Right Wing, 21=Left Wing, 12=Right Midfield, 16=Left Midfield",
        "shot_technique_ids": "**Shot Technique IDs:**",
        "shot_technique_values": "93=Normal, 95=Volley, 91=Half Volley, 90=Diving Header, 92=Lob, 94=Overhead Kick, 89=Backheel",
        "body_part_ids": "**Body Part IDs:**",
        "body_part_values": "40=Right Foot, 38=Left Foot, 37=Head, -1=Other",
        "shot_type_ids": "**Shot Type IDs:**",
        "shot_type_values": "87=Open Play, 62=Free Kick, 88=Penalty, 61=From Corner, -1=Other",
        "event_before_ids": "**Event Before Shot IDs:**",
        "event_before_values": "30=Pass, 43=Carry, 14=Dribble, 2=Ball Recovery, 10=Interception, 38=Miscontrol",
        
        # Mappings for UI options
        "regular_play": "Regular Play",
        "from_corner": "From Corner",
        "from_free_kick": "From Free Kick",
        "from_throw_in": "From Throw-in",
        "from_counter": "From Counter",
        "from_goal_kick": "From Goal Kick",
        "from_kick_off": "From Kick Off",
        
        "striker": "Striker",
        "secondary_striker": "Secondary Striker",
        "center_attacking_midfield": "Center Attacking Midfield",
        "right_wing": "Right Wing",
        "left_wing": "Left Wing",
        "right_midfield": "Right Midfield",
        "left_midfield": "Left Midfield",
        
        "normal": "Normal",
        "volley": "Volley",
        "half_volley": "Half Volley",
        "diving_header": "Diving Header",
        "lob": "Lob",
        "overhead_kick": "Overhead Kick",
        "backheel": "Backheel",
        
        "right_foot": "Right Foot",
        "left_foot": "Left Foot",
        "head": "Head",
        "other": "Other",
        
        "open_play": "Open Play",
        "free_kick": "Free Kick",
        "penalty": "Penalty",
        "from_corner_shot": "From Corner",
        "other_shot": "Other",
        
        "pass": "Pass",
        "carry": "Carry",
        "dribble": "Dribble",
        "ball_recovery": "Ball Recovery",
        "interception": "Interception",
        "miscontrol": "Miscontrol",
        
        # Error messages
        "model_load_error": "Failed to load model. Please check the model file.",
        "model_required": "Model file required to access prediction features.",
        "model_file_requirements": "Model File Requirements",
        "model_file_name": "File name: Must be exactly xg_model.joblib",
        "model_file_format": "Format: Joblib-serialized scikit-learn pipeline",
        "model_file_size": "Size: Typically 1-50 MB depending on model complexity",
        "model_features_title": "Model Input Features:",
        "model_features_desc": "Model must support the following 19 input features:",
        "troubleshooting": "Troubleshooting",
        "no_model_file": "If you don't have a model file:",
        "train_model": "Train a model using your data",
        "save_model": "Save it as: joblib.dump(model, 'xg_model.joblib')",
        "place_model": "Place it in:",
        "file_not_loading": "If the file exists but not loading:",
        "check_permissions": "Check file permissions",
        "valid_joblib": "Ensure it's a valid joblib file",
        "verify_compatibility": "Verify the model is compatible",
        "quick_help": "Quick Help",
        "steps_to_fix": "Steps to Fix:",
        "locate_model": "Locate your model file",
        "copy_to_root": "Copy to root directory", 
        "restart_app": "Restart application",
        "available_features": "Available Features",
        "after_model_setup": "After model setup:",
        "advanced_visualizations": "Advanced visualizations",
        "check_model_again": "🔄 Check Model Again",
        "click_refresh": "Click the refresh button below to check again",
        "model_not_found_title": "Model File Not Found",
        "required_action": "Required Action",
        "copy_model_instruction": "Please copy your trained model file",
        "to_path": "to",
        "model_missing_during_work": "Model Missing During Work",
        "work_preserved": "Your Work Has Been Preserved",
        "dont_worry": "Don't worry, your data is safe",
        "simulation_state_saved": "Simulation state is saved", 
        "settings_preserved": "Settings are preserved",
        "quick_fix": "Quick Fix",
        "restore_model": "Restore model file",
        "click_continue": "Click continue button below",
        "continue_work": "🔄 Continue Work",
        "model_still_missing": "Model still not found. Please ensure the file is placed correctly.",
        "no_shot_outcome": "N/A (no shot_outcome column)",
        "error_prefix": "Error:",
        
        # Language switcher
        "language": "Language",
        "switch_language": "Switch Language"
    }
}

def get_translation(key: str, lang: str = "en") -> str:
    """
    Get translation for a given key and language.
    
    Args:
        key: Translation key
        lang: Language code ('en' or 'id')
        
    Returns:
        Translated string or key if not found
    """
    return TRANSLATIONS.get(lang, {}).get(key, key)

def get_language_options(lang: str = "en") -> dict:
    """
    Get localized options for dropdowns based on language.
    
    Args:
        lang: Language code ('en' or 'id')
        
    Returns:
        Dictionary of localized options
    """
    t = TRANSLATIONS.get(lang, TRANSLATIONS["en"])
    
    return {
        "play_pattern": {
            t["regular_play"]: 1,
            t["from_corner"]: 2,
            t["from_free_kick"]: 3,
            t["from_throw_in"]: 4,
            t["from_counter"]: 6,
            t["from_goal_kick"]: 7,
            t["from_kick_off"]: 9
        },
        "position": {
            t["striker"]: 23,
            t["secondary_striker"]: 25,
            t["center_attacking_midfield"]: 19,
            t["right_wing"]: 17,
            t["left_wing"]: 21,
            t["right_midfield"]: 12,
            t["left_midfield"]: 16
        },
        "shot_technique": {
            t["normal"]: 93,
            t["volley"]: 95,
            t["half_volley"]: 91,
            t["diving_header"]: 90,
            t["lob"]: 92,
            t["overhead_kick"]: 94,
            t["backheel"]: 89
        },
        "shot_body_part": {
            t["right_foot"]: 40,
            t["left_foot"]: 38,
            t["head"]: 37,
            t["other"]: -1
        },
        "shot_type": {
            t["open_play"]: 87,
            t["free_kick"]: 62,
            t["penalty"]: 88,
            t["from_corner_shot"]: 61,
            t["other_shot"]: -1
        },
        "type_before": {
            t["pass"]: 30,
            t["carry"]: 43,
            t["dribble"]: 14,
            t["ball_recovery"]: 2,
            t["interception"]: 10,
            t["miscontrol"]: 38
        }
    }
